### PR TITLE
Task 2: Added Serverless configuration and tested it on AWS

### PR DESCRIPTION
**Pull request by maksym-lebedynets**
Manual deployment links
S3 - http://test-bucket-app-name.s3-website-us-east-1.amazonaws.com/
CloudFront - https://d3shp9cqsk86ve.cloudfront.net/

Automated deployment link:
Link to the CloudFront: https://d1o9fd88rx6kla.cloudfront.net/

### CODE REVIEW

**Comment by LoraBard** [comment]
Hi. Can you please provide links to S3 (manual and automated deployment) and cloudFront (manual deployment)? See [https://docs.google.com/spreadsheets/d/1jzhWxrBIqmXo0ZFBvdt-fd2stoabvVtdkd1QBbqGygQ/edit#gid=1386834576](https://docs.google.com/spreadsheets/d/1jzhWxrBIqmXo0ZFBvdt-fd2stoabvVtdkd1QBbqGygQ/edit#gid=1386834576)

**Comment by maksym-lebedynets** [comment]
> Hi. Can you please provide links to S3 (manual and automated deployment) and cloudFront (manual deployment)? See https://docs.google.com/spreadsheets/d/1jzhWxrBIqmXo0ZFBvdt-fd2stoabvVtdkd1QBbqGygQ/edit#gid=1386834576

Hello. Sure
Manual deployment links
S3 - http://test-bucket-app-name.s3-website-us-east-1.amazonaws.com/
CloudFront - https://d3shp9cqsk86ve.cloudfront.net/

**Comment by LoraBard** [comment]
> > Hi. Can you please provide links to S3 (manual and automated deployment) and cloudFront (manual deployment)? See https://docs.google.com/spreadsheets/d/1jzhWxrBIqmXo0ZFBvdt-fd2stoabvVtdkd1QBbqGygQ/edit#gid=1386834576
> 
> Hello. Sure
> Manual deployment links
> S3 - http://test-bucket-app-name.s3-website-us-east-1.amazonaws.com/
> CloudFront - https://d3shp9cqsk86ve.cloudfront.net/

Why S3 website shows 404 not found? (Should be 403). Did you provide right link to S3?

**Comment by maksym-lebedynets** [comment]
> > > Hi. Can you please provide links to S3 (manual and automated deployment) and cloudFront (manual deployment)? See https://docs.google.com/spreadsheets/d/1jzhWxrBIqmXo0ZFBvdt-fd2stoabvVtdkd1QBbqGygQ/edit#gid=1386834576
> > 
> > 
> > Hello. Sure
> > Manual deployment links
> > S3 - http://test-bucket-app-name.s3-website-us-east-1.amazonaws.com/
> > CloudFront - https://d3shp9cqsk86ve.cloudfront.net/
> 
> Why S3 website shows 404 not found? (Should be 403). Did you provide right link to S3?

I've just disabled public hosting. Now disabled it with 403. Could you check it again?

**Pull request merged**
